Homepage insertion: 'Nieuws en inzichten'
frameless/gemeentevoorbeeld.nl pull request #390
Opened 2024-02-13 11:07 UTC by ryanvvalkenhoef

2024-02-13 16:28 UTC, Robbert requested changes
We houden nog steeds van je!

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  max-inline-size: calc(var(--utrecht-article-max-inline-size) * 1.6);
Refactor dit naar:

```css
.voorbeeld-theme {
  --voorbeeld-page-content-max-inline-size: calc(var(--utrecht-article-max-inline-size) * 1.6);`
}

.voorbeeld-section-content {
   max-inline-size: calc(var(--utrecht-article-max-inline-size) * 1.6);
}
```

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  padding-block: var(--voorbeeld-space-block-cat);
Misschien kan deze padding block de default zijn voor alle `.voorbeeld-section`s?

De background color is niet nodig, de parent is al wit.

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
>  }
Je kunt overwegen die grijze achtegrond te geven aan alle even/oneven sections:

```css
.voorbeeld-section-content:nth-of-type(odd) {
  ...
}
```

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  grid-gap: 1rem;
Ik zou hier een space token verwachten.

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  border-block-start: 0.15em solid var(--voorbeeld-color-gray-200);
Ik stel voor om een border om de hele card te doen, dat is een iets minder eigenzinnig design — dat past beter bij gemeente Voorbeeld.

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  border-block-start: 0.15em solid var(--voorbeeld-color-gray-200);
Als je helemaal los wilt gaan, dan doe je voor [`prefers-contrast: more`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast) een donkerdere border grijs

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +
Maak hier anders een losse component van, `voorbeeld-column-layout`

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  max-inline-size: calc(100% - 752px);
magic number! 752 moet echt uitgelegd worden, met een comment of een variable

2024-02-13 16:28 UTC, Robbert commented on packages/next-templates/src/app/globals.css
> +  padding-inline-end: var(--voorbeeld-space-inline-cat);
Ik weet het niet zeker, maar zou dit niet een `inline-gap` kunnen zijn in de `.voorbeeld-column-layout`? Die dient dan als minimumafstand, je kunt alsnog met alignemnt de openingstijden verder opzij zetten.

2024-02-14 10:43 UTC, ryanvvalkenhoef commented on packages/next-templates/src/app/globals.css
>  }
Opgelost met een 'voorbeeld-section--alternate' class

2024-02-22 10:26 UTC, closed without merging